# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ApplicationApplicationIDInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, keypeer_api_key: str=None, application_id: str=None):  # noqa: E501
        """ApplicationApplicationIDInner - a model defined in Swagger

        :param keypeer_api_key: The keypeer_api_key of this ApplicationApplicationIDInner.  # noqa: E501
        :type keypeer_api_key: str
        :param application_id: The application_id of this ApplicationApplicationIDInner.  # noqa: E501
        :type application_id: str
        """
        self.swagger_types = {
            'keypeer_api_key': str,
            'application_id': str
        }

        self.attribute_map = {
            'keypeer_api_key': 'keypeer_api_key',
            'application_id': 'application_id'
        }
        self._keypeer_api_key = keypeer_api_key
        self._application_id = application_id

    @classmethod
    def from_dict(cls, dikt) -> 'ApplicationApplicationIDInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The application_applicationID_inner of this ApplicationApplicationIDInner.  # noqa: E501
        :rtype: ApplicationApplicationIDInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def keypeer_api_key(self) -> str:
        """Gets the keypeer_api_key of this ApplicationApplicationIDInner.


        :return: The keypeer_api_key of this ApplicationApplicationIDInner.
        :rtype: str
        """
        return self._keypeer_api_key

    @keypeer_api_key.setter
    def keypeer_api_key(self, keypeer_api_key: str):
        """Sets the keypeer_api_key of this ApplicationApplicationIDInner.


        :param keypeer_api_key: The keypeer_api_key of this ApplicationApplicationIDInner.
        :type keypeer_api_key: str
        """

        self._keypeer_api_key = keypeer_api_key

    @property
    def application_id(self) -> str:
        """Gets the application_id of this ApplicationApplicationIDInner.


        :return: The application_id of this ApplicationApplicationIDInner.
        :rtype: str
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id: str):
        """Sets the application_id of this ApplicationApplicationIDInner.


        :param application_id: The application_id of this ApplicationApplicationIDInner.
        :type application_id: str
        """

        self._application_id = application_id
