# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ApplicationApplicationIDProviderIDInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, service_api_key: str=None, expiry: str=None):  # noqa: E501
        """ApplicationApplicationIDProviderIDInner - a model defined in Swagger

        :param service_api_key: The service_api_key of this ApplicationApplicationIDProviderIDInner.  # noqa: E501
        :type service_api_key: str
        :param expiry: The expiry of this ApplicationApplicationIDProviderIDInner.  # noqa: E501
        :type expiry: str
        """
        self.swagger_types = {
            'service_api_key': str,
            'expiry': str
        }

        self.attribute_map = {
            'service_api_key': 'service_api_key',
            'expiry': 'expiry'
        }
        self._service_api_key = service_api_key
        self._expiry = expiry

    @classmethod
    def from_dict(cls, dikt) -> 'ApplicationApplicationIDProviderIDInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The application_applicationID_providerID_inner of this ApplicationApplicationIDProviderIDInner.  # noqa: E501
        :rtype: ApplicationApplicationIDProviderIDInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_api_key(self) -> str:
        """Gets the service_api_key of this ApplicationApplicationIDProviderIDInner.


        :return: The service_api_key of this ApplicationApplicationIDProviderIDInner.
        :rtype: str
        """
        return self._service_api_key

    @service_api_key.setter
    def service_api_key(self, service_api_key: str):
        """Sets the service_api_key of this ApplicationApplicationIDProviderIDInner.


        :param service_api_key: The service_api_key of this ApplicationApplicationIDProviderIDInner.
        :type service_api_key: str
        """

        self._service_api_key = service_api_key

    @property
    def expiry(self) -> str:
        """Gets the expiry of this ApplicationApplicationIDProviderIDInner.

        ISO 8601 Format  # noqa: E501

        :return: The expiry of this ApplicationApplicationIDProviderIDInner.
        :rtype: str
        """
        return self._expiry

    @expiry.setter
    def expiry(self, expiry: str):
        """Sets the expiry of this ApplicationApplicationIDProviderIDInner.

        ISO 8601 Format  # noqa: E501

        :param expiry: The expiry of this ApplicationApplicationIDProviderIDInner.
        :type expiry: str
        """

        self._expiry = expiry
