# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ApplicationInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, application_id: int=None, uuid: str=None, name: str=None, uri: str=None):  # noqa: E501
        """ApplicationInner - a model defined in Swagger

        :param application_id: The application_id of this ApplicationInner.  # noqa: E501
        :type application_id: int
        :param uuid: The uuid of this ApplicationInner.  # noqa: E501
        :type uuid: str
        :param name: The name of this ApplicationInner.  # noqa: E501
        :type name: str
        :param uri: The uri of this ApplicationInner.  # noqa: E501
        :type uri: str
        """
        self.swagger_types = {
            'application_id': int,
            'uuid': str,
            'name': str,
            'uri': str
        }

        self.attribute_map = {
            'application_id': 'application_id',
            'uuid': 'uuid',
            'name': 'name',
            'uri': 'uri'
        }
        self._application_id = application_id
        self._uuid = uuid
        self._name = name
        self._uri = uri

    @classmethod
    def from_dict(cls, dikt) -> 'ApplicationInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The application_inner of this ApplicationInner.  # noqa: E501
        :rtype: ApplicationInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def application_id(self) -> int:
        """Gets the application_id of this ApplicationInner.


        :return: The application_id of this ApplicationInner.
        :rtype: int
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id: int):
        """Sets the application_id of this ApplicationInner.


        :param application_id: The application_id of this ApplicationInner.
        :type application_id: int
        """

        self._application_id = application_id

    @property
    def uuid(self) -> str:
        """Gets the uuid of this ApplicationInner.


        :return: The uuid of this ApplicationInner.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this ApplicationInner.


        :param uuid: The uuid of this ApplicationInner.
        :type uuid: str
        """

        self._uuid = uuid

    @property
    def name(self) -> str:
        """Gets the name of this ApplicationInner.


        :return: The name of this ApplicationInner.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ApplicationInner.


        :param name: The name of this ApplicationInner.
        :type name: str
        """

        self._name = name

    @property
    def uri(self) -> str:
        """Gets the uri of this ApplicationInner.


        :return: The uri of this ApplicationInner.
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri: str):
        """Sets the uri of this ApplicationInner.


        :param uri: The uri of this ApplicationInner.
        :type uri: str
        """

        self._uri = uri
