# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ConsumerProviderInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, consumer_id: str=None, provider_id: str=None, service_api_key: str=None, expiry: str=None):  # noqa: E501
        """ConsumerProviderInner - a model defined in Swagger

        :param consumer_id: The consumer_id of this ConsumerProviderInner.  # noqa: E501
        :type consumer_id: str
        :param provider_id: The provider_id of this ConsumerProviderInner.  # noqa: E501
        :type provider_id: str
        :param service_api_key: The service_api_key of this ConsumerProviderInner.  # noqa: E501
        :type service_api_key: str
        :param expiry: The expiry of this ConsumerProviderInner.  # noqa: E501
        :type expiry: str
        """
        self.swagger_types = {
            'consumer_id': str,
            'provider_id': str,
            'service_api_key': str,
            'expiry': str
        }

        self.attribute_map = {
            'consumer_id': 'consumer_id',
            'provider_id': 'provider_id',
            'service_api_key': 'service_api_key',
            'expiry': 'expiry'
        }
        self._consumer_id = consumer_id
        self._provider_id = provider_id
        self._service_api_key = service_api_key
        self._expiry = expiry

    @classmethod
    def from_dict(cls, dikt) -> 'ConsumerProviderInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The consumer_provider_inner of this ConsumerProviderInner.  # noqa: E501
        :rtype: ConsumerProviderInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def consumer_id(self) -> str:
        """Gets the consumer_id of this ConsumerProviderInner.


        :return: The consumer_id of this ConsumerProviderInner.
        :rtype: str
        """
        return self._consumer_id

    @consumer_id.setter
    def consumer_id(self, consumer_id: str):
        """Sets the consumer_id of this ConsumerProviderInner.


        :param consumer_id: The consumer_id of this ConsumerProviderInner.
        :type consumer_id: str
        """

        self._consumer_id = consumer_id

    @property
    def provider_id(self) -> str:
        """Gets the provider_id of this ConsumerProviderInner.


        :return: The provider_id of this ConsumerProviderInner.
        :rtype: str
        """
        return self._provider_id

    @provider_id.setter
    def provider_id(self, provider_id: str):
        """Sets the provider_id of this ConsumerProviderInner.


        :param provider_id: The provider_id of this ConsumerProviderInner.
        :type provider_id: str
        """

        self._provider_id = provider_id

    @property
    def service_api_key(self) -> str:
        """Gets the service_api_key of this ConsumerProviderInner.


        :return: The service_api_key of this ConsumerProviderInner.
        :rtype: str
        """
        return self._service_api_key

    @service_api_key.setter
    def service_api_key(self, service_api_key: str):
        """Sets the service_api_key of this ConsumerProviderInner.


        :param service_api_key: The service_api_key of this ConsumerProviderInner.
        :type service_api_key: str
        """

        self._service_api_key = service_api_key

    @property
    def expiry(self) -> str:
        """Gets the expiry of this ConsumerProviderInner.

        ISO 8601 Format  # noqa: E501

        :return: The expiry of this ConsumerProviderInner.
        :rtype: str
        """
        return self._expiry

    @expiry.setter
    def expiry(self, expiry: str):
        """Sets the expiry of this ConsumerProviderInner.

        ISO 8601 Format  # noqa: E501

        :param expiry: The expiry of this ConsumerProviderInner.
        :type expiry: str
        """

        self._expiry = expiry
