# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ConsumerInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, consumer_id: int=None, uuid: str=None):  # noqa: E501
        """ConsumerInner - a model defined in Swagger

        :param consumer_id: The consumer_id of this ConsumerInner.  # noqa: E501
        :type consumer_id: int
        :param uuid: The uuid of this ConsumerInner.  # noqa: E501
        :type uuid: str
        """
        self.swagger_types = {
            'consumer_id': int,
            'uuid': str
        }

        self.attribute_map = {
            'consumer_id': 'consumer_id',
            'uuid': 'uuid'
        }
        self._consumer_id = consumer_id
        self._uuid = uuid

    @classmethod
    def from_dict(cls, dikt) -> 'ConsumerInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The consumer_inner of this ConsumerInner.  # noqa: E501
        :rtype: ConsumerInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def consumer_id(self) -> int:
        """Gets the consumer_id of this ConsumerInner.


        :return: The consumer_id of this ConsumerInner.
        :rtype: int
        """
        return self._consumer_id

    @consumer_id.setter
    def consumer_id(self, consumer_id: int):
        """Sets the consumer_id of this ConsumerInner.


        :param consumer_id: The consumer_id of this ConsumerInner.
        :type consumer_id: int
        """

        self._consumer_id = consumer_id

    @property
    def uuid(self) -> str:
        """Gets the uuid of this ConsumerInner.


        :return: The uuid of this ConsumerInner.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this ConsumerInner.


        :param uuid: The uuid of this ConsumerInner.
        :type uuid: str
        """

        self._uuid = uuid
