# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ConsumerConsumerAddAppplication(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, consumer_id: str=None, keypeer_api_key: str=None, application_id: str=None, expiry: str=None):  # noqa: E501
        """ConsumerConsumerAddAppplication - a model defined in Swagger

        :param consumer_id: The consumer_id of this ConsumerConsumerAddAppplication.  # noqa: E501
        :type consumer_id: str
        :param keypeer_api_key: The keypeer_api_key of this ConsumerConsumerAddAppplication.  # noqa: E501
        :type keypeer_api_key: str
        :param application_id: The application_id of this ConsumerConsumerAddAppplication.  # noqa: E501
        :type application_id: str
        :param expiry: The expiry of this ConsumerConsumerAddAppplication.  # noqa: E501
        :type expiry: str
        """
        self.swagger_types = {
            'consumer_id': str,
            'keypeer_api_key': str,
            'application_id': str,
            'expiry': str
        }

        self.attribute_map = {
            'consumer_id': 'consumer_id',
            'keypeer_api_key': 'keypeer_api_key',
            'application_id': 'application_id',
            'expiry': 'expiry'
        }
        self._consumer_id = consumer_id
        self._keypeer_api_key = keypeer_api_key
        self._application_id = application_id
        self._expiry = expiry

    @classmethod
    def from_dict(cls, dikt) -> 'ConsumerConsumerAddAppplication':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The consumer_consumerAddAppplication of this ConsumerConsumerAddAppplication.  # noqa: E501
        :rtype: ConsumerConsumerAddAppplication
        """
        return util.deserialize_model(dikt, cls)

    @property
    def consumer_id(self) -> str:
        """Gets the consumer_id of this ConsumerConsumerAddAppplication.


        :return: The consumer_id of this ConsumerConsumerAddAppplication.
        :rtype: str
        """
        return self._consumer_id

    @consumer_id.setter
    def consumer_id(self, consumer_id: str):
        """Sets the consumer_id of this ConsumerConsumerAddAppplication.


        :param consumer_id: The consumer_id of this ConsumerConsumerAddAppplication.
        :type consumer_id: str
        """

        self._consumer_id = consumer_id

    @property
    def keypeer_api_key(self) -> str:
        """Gets the keypeer_api_key of this ConsumerConsumerAddAppplication.


        :return: The keypeer_api_key of this ConsumerConsumerAddAppplication.
        :rtype: str
        """
        return self._keypeer_api_key

    @keypeer_api_key.setter
    def keypeer_api_key(self, keypeer_api_key: str):
        """Sets the keypeer_api_key of this ConsumerConsumerAddAppplication.


        :param keypeer_api_key: The keypeer_api_key of this ConsumerConsumerAddAppplication.
        :type keypeer_api_key: str
        """

        self._keypeer_api_key = keypeer_api_key

    @property
    def application_id(self) -> str:
        """Gets the application_id of this ConsumerConsumerAddAppplication.


        :return: The application_id of this ConsumerConsumerAddAppplication.
        :rtype: str
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id: str):
        """Sets the application_id of this ConsumerConsumerAddAppplication.


        :param application_id: The application_id of this ConsumerConsumerAddAppplication.
        :type application_id: str
        """

        self._application_id = application_id

    @property
    def expiry(self) -> str:
        """Gets the expiry of this ConsumerConsumerAddAppplication.

        ISO 8601 Format  # noqa: E501

        :return: The expiry of this ConsumerConsumerAddAppplication.
        :rtype: str
        """
        return self._expiry

    @expiry.setter
    def expiry(self, expiry: str):
        """Sets the expiry of this ConsumerConsumerAddAppplication.

        ISO 8601 Format  # noqa: E501

        :param expiry: The expiry of this ConsumerConsumerAddAppplication.
        :type expiry: str
        """

        self._expiry = expiry
