# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ConsumerProviderIDInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, provider_id: str=None, service_api_key: str=None):  # noqa: E501
        """ConsumerProviderIDInner - a model defined in Swagger

        :param provider_id: The provider_id of this ConsumerProviderIDInner.  # noqa: E501
        :type provider_id: str
        :param service_api_key: The service_api_key of this ConsumerProviderIDInner.  # noqa: E501
        :type service_api_key: str
        """
        self.swagger_types = {
            'provider_id': str,
            'service_api_key': str
        }

        self.attribute_map = {
            'provider_id': 'provider_id',
            'service_api_key': 'service_api_key'
        }
        self._provider_id = provider_id
        self._service_api_key = service_api_key

    @classmethod
    def from_dict(cls, dikt) -> 'ConsumerProviderIDInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The consumer_providerID_inner of this ConsumerProviderIDInner.  # noqa: E501
        :rtype: ConsumerProviderIDInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def provider_id(self) -> str:
        """Gets the provider_id of this ConsumerProviderIDInner.


        :return: The provider_id of this ConsumerProviderIDInner.
        :rtype: str
        """
        return self._provider_id

    @provider_id.setter
    def provider_id(self, provider_id: str):
        """Sets the provider_id of this ConsumerProviderIDInner.


        :param provider_id: The provider_id of this ConsumerProviderIDInner.
        :type provider_id: str
        """

        self._provider_id = provider_id

    @property
    def service_api_key(self) -> str:
        """Gets the service_api_key of this ConsumerProviderIDInner.


        :return: The service_api_key of this ConsumerProviderIDInner.
        :rtype: str
        """
        return self._service_api_key

    @service_api_key.setter
    def service_api_key(self, service_api_key: str):
        """Sets the service_api_key of this ConsumerProviderIDInner.


        :param service_api_key: The service_api_key of this ConsumerProviderIDInner.
        :type service_api_key: str
        """

        self._service_api_key = service_api_key
